### ISSUE TITLE
Constructor fails with non-file FileObject

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracpete/vfsjfilechooser2#5]
```
What steps will reproduce the problem?
1. Create a FileObject which is not backed by a file:/// URI 
2. Create a VFSJFileChooser(FileObject)

    java.lang.IllegalArgumentException: URI scheme is not "file"
        at java.io.File.<init>(File.java:395)
        at com.googlecode.vfsjfilechooser2.utils.DefaultFileObjectConverter.convertFileObject(DefaultFileObjectConverter.java:51)
        at com.googlecode.vfsjfilechooser2.VFSJFileChooser.getCurrentDirectory(VFSJFileChooser.java:541)
        at com.googlecode.vfsjfilechooser2.plaf.metal.MetalVFSFileChooserUI$DirectoryComboBoxAction.actionPerformed(MetalVFSFileChooserUI.java:1569)
        at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260)
        at javax.swing.JComboBox.setSelectedItem(JComboBox.java:588)
        at com.googlecode.vfsjfilechooser2.plaf.metal.MetalVFSFileChooserUI.doDirectoryChanged(MetalVFSFileChooserUI.java:804)
        at com.googlecode.vfsjfilechooser2.plaf.metal.MetalVFSFileChooserUI.access$600(MetalVFSFileChooserUI.java:94)
        at com.googlecode.vfsjfilechooser2.plaf.metal.MetalVFSFileChooserUI$6.propertyChange(MetalVFSFileChooserUI.java:958)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
        at java.awt.Component.firePropertyChange(Component.java:8382)
        at com.googlecode.vfsjfilechooser2.VFSJFileChooser.setCurrentDirectoryObject(VFSJFileChooser.java:635)
        at com.googlecode.vfsjfilechooser2.VFSJFileChooser.<init>(VFSJFileChooser.java:229)
        at com.googlecode.vfsjfilechooser2.VFSJFileChooser.<init>(VFSJFileChooser.java:209)

Defeats the point, a little. :-(
```

Original issue reported on code.google.com by `shevek.h...@googlemail.com` on 6 Jan 2014 at 6:49

**Comment by thomasX** [comment]
fixed in commit b3caf6931b38738a91e56f9d0113d98c7c918bb4
